CUDA_VISIBLE_DEVICES=0,1 TOKENIZERS_PARALLELISM=false WANDB_DISABLED=true python run_qa.py \
  --model_name_or_path hfl/chinese-macbert-large \
  --train_file ./data/all.json \
  --test_file ./data/test.json \
  --do_train True \
  --do_predict True \
  --per_device_train_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --learning_rate 1e-5 \
  --max_steps 5000 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir ./results/macbert_runqa/ \
  --save_total_limit 3 \